server:
  port: 9191
  
  
spring:
 application:
   name: API-GATEWAY
 cloud:
   gateway:
    routes:
     - id: PERSON-SERVICE
       uri: lb://PERSON-SERVICE
       predicates:
        - Path=/user/**
     - id: BOOKKEEPER-SERVICE
       uri: lb://BOOKKEEPER-SERVICE
       predicates:
        - Path=/pay/**
